export const RANDOM_VALUE='RANDOM_VALUE'
export const EXCHANGE='EXCHANGE'
export const INPUT_VALUE='INPUT_VALUE'
export const RESET='RESET'
export const INPUT_COIN='INPUT_COIN'
export const UPDATE_STATE_COINS = 'UPDATE_STATE_COINS'

